---
- name: include prerequisite_rhcs_iso_install_debian.yml
  include: prerequisite_rhcs_iso_install_debian.yml
  when:
    - ceph_repository_type == 'iso'

- name: include prerequisite_rhcs_cdn_install_debian.yml
  include: prerequisite_rhcs_cdn_install_debian.yml
  when:
    - ceph_repository_type == 'cdn'
