---
- name: install redhat dependencies
  package:
    name: "{{ redhat_package_dependencies }}"
    state: present
  when:
    - ansible_distribution == 'RedHat'

- name: install centos dependencies
  yum:
    name: "{{ centos_package_dependencies }}"
    state: present
  when:
    - ansible_distribution == 'CentOS'

- name: Install redhat dependencies with Pip
  pip:
    executable: /usr/bin/pip
    name: "{{ item }}"
  with_items:
    - "{{ redhat_package_dependencies_pip }}"
  when:
    - ansible_distribution == 'RedHat'

- name: Install centos dependencies with Pip
  pip:
    executable: /usr/bin/pip
    name: "{{ item }}"
  with_items:
    - "{{ centos_package_dependencies_pip }}"
  when:
    - ansible_distribution == 'CentOS'
    
- name: install redhat ceph-common
  package:
    name: "ceph-common"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"

- name: install redhat ceph-mon package
  package:
    name: "ceph-mon"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mon_group_name in group_names

- name: install redhat ceph-osd package
  package:
    name: "ceph-osd"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - osd_group_name in group_names

- name: install redhat ceph-fuse package
  package:
    name: "ceph-fuse"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names

- name: install redhat ceph-base package
  package:
    name: "ceph-base"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names

- name: install redhat ceph-test package
  package:
    name: ceph-test
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - ceph_test

- name: install redhat ceph-radosgw package
  package:
    name: ceph-radosgw
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - rgw_group_name in group_names
